#!/bin/bash

# https://gist.github.com/robwierzbowski/5430952/
# Create and push to a new github repo from the command line.
# Grabs sensible defaults from the containing folder and `.gitconfig`.
# Refinements welcome.

# Gather constant vars
CURRENTDIR=${PWD##*/}
GITHUBUSER=$(git config github.user)

# Get user input
read -p "New package name (enter for ${PWD##*/}): " REPONAME
read -p "Repo Description: " DESCRIPTION
read -p "Project Namespace: " NAMESPACE

echo "Here we go..."
# Curl some json to the github API oh damn we so fancy
curl -u ${GITHUBUSER} https://api.github.com/orgs/TownOfCary/repos -d "{\"name\": \"${REPONAME:-${CURRENTDIR}}\", \"description\": \"${DESCRIPTION}\", \"private\": false, \"has_issues\": true, \"has_downloads\": true, \"has_wiki\": false}"

# Set the freshly created repo to the origin and push
# You'll need to have added your public key to your github account
FULLREPONAME=$(echo ${REPONAME:-${CURRENTDIR}} | sed -e "s/ /-/g")
echo $FULLREPONAME
git remote set-url origin git@github.com:TownOfCary/${FULLREPONAME}.git
git remote -v

sed -i -e "s/@@@/${NAMESPACE}/g" ./src/classes/PackageUtils.cls
sed -i -e "s/@PACKAGE_NAME@/${REPONAME}/g" ./src/classes/PackageScripts.cls
git add ./src

echo "src/classes/PackageUtils.cls
src/classes/PackageUtils.cls-meta.xml
src/project_setup" >> .gitignore

git add .gitignore

git commit -m "Updated namespace of current project and added PackageUtils to .gitignore"
git push --set-upstream origin master

git checkout -b dev
git push -u origin dev
