#!/bin/bash

# https://gist.github.com/robwierzbowski/5430952/
# Create and push to a new github repo from the command line.  
# Grabs sensible defaults from the containing folder and `.gitconfig`.  
# Refinements welcome.

# Gather constant vars
CURRENTDIR=${PWD##*/}
GITHUBUSER=$(git config github.user)

# Get user input
read -p "New repo name (enter for ${PWD##*/}): " REPONAME
read -p "Repo Description:" DESCRIPTION

echo "Here we go..."
# Curl some json to the github API oh damn we so fancy
curl -u ${GITHUBUSER} https://api.github.com/orgs/TownOfCary/repos -d "{\"name\": \"${REPONAME:-${CURRENTDIR}}\", \"description\": \"${DESCRIPTION}\", \"private\": false, \"has_issues\": true, \"has_downloads\": true, \"has_wiki\": false}"

# Set the freshly created repo to the origin and push
# You'll need to have added your public key to your github account
git remote set-url origin git@github.com:TownOfCary/${REPONAME:-${CURRENTDIR}}.git
git push --set-upstream origin master
git checkout -b dev
git push -u origin dev
